db = "fjall"                 # path to store rocksdb
index_path = "search_index"  # path to store index
index_with_full_text = false # whether establish full-text index
addr = "127.0.0.1:8081"      # If allow LAN access, change it to "0.0.0.0:port".

# The raw data path you downloaded from the torrent, and you must NOT unzip it.
raw_data_path = "裁判文书全量数据（已完成）"
